site_name: C1ph3rx13
repo_name: C1ph3rx13.github.io
site_description: C1ph3rx13
repo_url: https://github.com/C1ph3rX13/C1ph3rX13.github.io
copyright: Copyright &copy 2025 C1ph3rx13
edit_uri: https://github.com/C1ph3rX13/C1ph3rX13.github.io/tree/main/docs

# 禁用路由导航方式
# use_directory_urls: false

# 主题设置
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  font:
    text: "Maple Mono CN"
    code: "Maple Mono CN"
    features:
      - "liga"  # 启用连字
      - "calt"  # 启用上下文替代
  features:
    - search.highlight
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - content.action.edit
    - content.code.copy
    - content.tables
    - content.tables.scroll  # 横向滚动
    - content.tables.hover   # 悬停高亮
    - content.tables.sort    # 列排序（Material 8.0+）

  # 亮色/深色模式
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: 切换至亮色模式

# markdown特性设置
markdown_extensions:
  - admonition # 提醒框、警告框等
  - md_in_html # 支持嵌入HTML代码
  - pymdownx.details # 支持<details>折叠标签
  - pymdownx.tilde # 支持~表示删除的文本
  - pymdownx.magiclink # 自动将URL转换为可点击的链接
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 4
      anchorlink: true
  # mermaid渲染
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark  # 支持表格内标记文本（如荧光笔效果）
  - pymdownx.caret  # 支持上标/下标

plugins:
  - search:
      separator: '[\s\u200b\-]'
  - awesome-pages:
      collapse_single_pages: true
      strict: false

extra:
  generator: false # 去除页脚广告
  social: # 页脚链接
    - icon: fontawesome/brands/github
      link: https://github.com/C1ph3rX13
    - icon: material/file-document
      link: https://github.com/C1ph3rX13

extra_css:
  - "https://chinese-fonts-cdn.deno.dev/packages/maple-mono-cn/dist/MapleMono-CN-Regular/result.css"